import "../styles/global.css";
import type { Metadata } from "next";
import { Locale, i18n } from "$/i18n.config";
import Header from "../components/Header";
import { Inter } from "next/font/google";
import themeHandler from "@/lib/theme";
import { useEffect, useState } from "react";
import { Appearance } from "@/types/general";
import ThemeSwitcher from "@/components/ThemeSwitcher";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: Locale } }) {
  return (
    <html lang={params.lang}>
      <body className={`bg-primary w-full ${inter.className} px-5`}>
        <Header lang={params.lang} />
        <main>{children}</main>
        <ThemeSwitcher />
      </body>
    </html>
  );
}
