import "@/styles/global.css";
import type { Metadata } from "next";
import { Locale, LocaleLabel, i18n } from "$/i18n.config";
import Header from "@/components/Header";
import { Inter, Vazirmatn } from "next/font/google";
import ThemeSwitcher from "@/components/ThemeSwitcher";
const inter = Inter({ subsets: ["latin"] });
const vazir = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale.label, dir: locale.dir }));
}

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: LocaleLabel, dir: 'string' } }) {
  return (
    <html lang={params.lang} data-theme="dark" dir={params.dir}>
      <body className={`bg-primary w-full ${inter.className}`}>
        <Header lang={params.lang} />
        <main>{children}</main>
        <ThemeSwitcher />
      </body>
    </html>
  );
}
